import type { SessionMeta } from "@/lib/storage/chatStorage";
import type { ChatMessage } from "@/lib/types/chat";
import type { Artifact } from "@/lib/stores/assets/artifacts";
import type { StoredDocument } from "@/lib/documents/types";
import type { UserNote } from "@/lib/notes/userNote";
import type { ReviewCard } from "@/lib/review/types";
import type { ImageGenSession } from "@/lib/stores/assets/imageGen";
import type { ChatProjectSyncPayload, ChatSessionSyncPayload, CloudSyncKind, SyncDocumentRow } from "./types";
export interface CloudSyncStores {
  hasCloudRevision?: (kind: CloudSyncKind, id: string) => boolean;
  applyCloudHead?:(row:SyncDocumentRow)=>boolean;
  listImageIds?:()=>string[];
  getImage?:(id:string)=>Promise<ImageGenSession|null>;
  applyImage?:(row:ImageGenSession)=>Promise<void>;
  forgetImage?:(id:string)=>void;
  listSessionMetas: () => SessionMeta[];
  loadSession: (id: string) => Promise<{ meta: SessionMeta; messages: ChatMessage[] } | null>;
  applySession: (payload: ChatSessionSyncPayload) => void | Promise<void>;
  forgetSession: (id: string) => void | Promise<void>;
  listArtifactIds: () => string[];
  getArtifact: (id: string) => Artifact | null | Promise<Artifact | null>;
  applyArtifact: (artifact: Artifact) => void | Promise<void>;
  forgetArtifact: (id: string) => void;
  listDocumentIds: () => string[];
  getDocument: (id: string) => StoredDocument | null | Promise<StoredDocument | null>;
  applyDocument: (doc: StoredDocument) => void | Promise<void>;
  forgetDocument: (id: string) => void;
  listNoteIds: () => string[];
  getNote: (id: string) => UserNote | null;
  applyNote: (note: UserNote) => void;
  forgetNote: (id: string) => void;
  listCardIds: () => string[];
  getCard: (id: string) => ReviewCard | null;
  applyCard: (card: ReviewCard) => void;
  forgetCard: (id: string) => void;
  listProjectIds: () => string[];
  getProject: (id: string) => ChatProjectSyncPayload | null;
  applyProject: (project: ChatProjectSyncPayload) => void;
  forgetProject: (id: string) => void;
}
